_BASE_: "Base-Panoptic-FPN-MD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (6000, 8000)
  MAX_ITER: 500
TEST:
  EVAL_PERIOD: 300